name: edsushy_shop
description: "A complete e-commerce Flutter application with admin and customer roles, M-Pesa payments, and full product management."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^4.4.0
  firebase_auth: ^6.1.4
  cloud_firestore: ^6.1.2
  firebase_storage: ^13.0.6
  google_sign_in: ^7.2.0
  
  # State Management
  provider: ^6.1.2
  
  # Image & File Handling
  image_picker: ^1.0.4
  
  # UI
  shimmer: ^3.0.0
  google_fonts: ^6.2.1
  shared_preferences: ^2.3.2
  
  # Networking
  http: ^1.2.0

  # Supabase Storage
  supabase_flutter: ^2.5.0
  supabase: ^2.1.0
  uuid: ^4.0.0

  cupertino_icons: ^1.0.8
  file_picker: ^10.3.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  # Add your assets and fonts here as needed
  assets:
    - assets/images/
